In [1]:
import numpy as np

A = np.array([1,1,1])

B = np.array([2,2,2])

In [5]:
print(np.vstack((A,B)))  #vertical stack

C = np.vstack((A,B))

D = np.hstack((A,B))    #horizontal stack

[[1 1 1]
 [2 2 2]]


In [6]:
print(A.shape,C.shape)

print(D.shape)

(3,) (2, 3)
(6,)


In [8]:
print(A[np.newaxis,:].shape)

(1, 3)


In [10]:
print(A[:,np.newaxis].shape)

(3, 1)


In [ ]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

In [12]:
C = np.concatenate((A,B,B,A),axis = 1)   #多个array的合并
    
print(C)

[1 1 1 2 2 2 2 2 2 1 1 1]


In [13]:
C = np.concatenate((A,B,B,A),axis = 1)   #多个array的合并
    
print(C)

AxisError: axis 1 is out of bounds for array of dimension 1